version: '3.3'

services:

  wordpress:
      image: wordpress
      restart: always
      ports:
        - 4080:80
      volumes:
        - wordpress:/var/www/html
      environment:
        WORDPRESS_DB_PASSWORD: example

  mysql:
      image: mysql:5.7
      restart: always
      volumes:
        - db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: example

volumes:
  db:
  wordpress: